[1] "Error: Problem with `mutate()` input `COL_datetimec`.\n\033[31mx\033[39m could not find function \"mon2num\"\n\033[34mi\033[39m Input `COL_datetimec` is `paste0(...)`.\n\033[90mRun `rlang::last_error()` to see where the error occurred.\033[39m\n"

Error in eval(lhs, parent, parent) : object 'ulv' not found
 

Error in tabyl(ulv$VISITEVENT) : object 'ulv' not found
 

Error in is.data.frame(y) : object 'ulv' not found
 

Error in is.data.frame(y) : object 'ulv' not found
 

[1] "Error: Problem with `mutate()` input `COL_datetimec`.\n\033[31mx\033[39m could not find function \"mon2num\"\n\033[34mi\033[39m Input `COL_datetimec` is `paste0(...)`.\n\033[90mRun `rlang::last_error()` to see where the error occurred.\033[39m\n"

Error in tabyl(ulv$VISITEVENT) : object 'ulv' not found
 

Error in is.data.frame(y) : object 'ulv' not found
 

[1] "Error: Problem with `mutate()` input `COL_datetimec`.\n\033[31mx\033[39m could not find function \"mon2num\"\n\033[34mi\033[39m Input `COL_datetimec` is `paste0(...)`.\n\033[90mRun `rlang::last_error()` to see where the error occurred.\033[39m\n"

[1] "Error in log_print(x, ..., console = console, blank_after = blank_after,  : \n  argument \"x\" is missing, with no default\n"

[1] "Error: arrange() failed at implicit mutate() step. \n\033[31mx\033[39m Could not create a temporary column for `..2`.\n\033[34mi\033[39m `..2` is `col_datetime`.\n\033[90mRun `rlang::last_error()` to see where the error occurred.\033[39m\n"

[1] "Error: arrange() failed at implicit mutate() step. \n\033[31mx\033[39m Could not create a temporary column for `..2`.\n\033[34mi\033[39m `..2` is `col_datetime`.\n\033[90mRun `rlang::last_error()` to see where the error occurred.\033[39m\n"

Error: unexpected ',' in "                             ~ "Unscheduled Visit","
 

Error: unexpected ')' in "                           TRUE ~ EVENT)"
 

Error in arrange(SUBNUM, col_datetime) : object 'SUBNUM' not found
 

[1] "Error: object 'SUBNUM' not found\n\033[90mRun `rlang::last_error()` to see where the error occurred.\033[39m\n"

